### ISSUE TITLE
Write MVP spec

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/datapackage-ui#227]
# Description

We want to allow users to create, edit and validate Data Packages from a web interface.

We have an earlier version of this library [here](http://datapackagist.openknowledge.io). While we consider this implementation to be a bit flawed, it does show all the moving parts and useful implementation approaches for building out `datapackage-ui`.

The most important component is the use of [json-editor](https://github.com/jdorn/json-editor) to generate web forms out of JSON Schema files.

# Tasks

- [x] Write a short spec on the approach / design -> #230, #231, #232, #233
- [x] Create a new Data Package -> #230
- [x] Edit an existing Data Package -> #230
- [x] Validate a Data Package -> #230
- [x] Farm out Table Schema editing, on Tabular Data Packages, to [this](https://github.com/frictionlessdata/tableschema-ui) -> https://github.com/frictionlessdata/tableschema-ui/issues/1
- [x] Download as a `datapackage.json` descriptor -> #230
- [x] Ensure correct `how it works` section -> #233
- [x] Tests -> #233
- [x] Review extracted issues:
  - [x] #230
  - [x] #231 
  - [x] #232 
  - [x] #233
  - [x] https://github.com/frictionlessdata/tableschema-ui/issues/1

---

Visual design (see #228):
- Coded version of above: http://p.smth.uk/packagist/
- Source: https://github.com/smth/packagist/tree/master
- Build: https://github.com/smth/packagist/tree/gh-pages

--- 

This issue is split into smallest issues and now contains only spec writing to be finished.

**Comment by rufuspollock** [comment]
@pwalsh i think this is great - I'd welcome chance to chat a bit about this, especially as it connects with CLI UI work i'm doing.

**Comment by danfowler** [comment]
>  Download as a datapackage.json descriptor

I always found going through the old interface to download a standalone `datapackage.json` file somewhat confusing, especially when I go through `n` iterations on this or other interfaces and end up with files ranging up to `datapackage (n - 1).json` littering my `~/Downloads`.  Maybe an approach could be the following:

- what is actually downloaded is a zip file
- the zip file contains a `datapackage.json` at the root
- there is no data file
- there is a `README.md` at the root that provides very brief instructions on Data Packages and how to add the original data file (if the Data Package was created from a local data file)
- the name of the zip file is sourced from the Data Package descriptor's `name` field || `datapackage-{DATE}.zip`

**Comment by pwalsh** [comment]
@danfowler excellent suggestions!

**Comment by pwalsh** [comment]
> @pwalsh i think this is great - I'd welcome chance to chat a bit about this, especially as it connects with CLI UI work i'm doing.

@rufuspollock see the new design. we are all really happy with it. of course, iterations when it gets built, etc. Feedback in the coming 2-4 weeks would be great.

**Comment by rufuspollock** [comment]
@pwalsh the point of talking was how this could merge with other things 😄 - maybe something to talk about monday.

**Comment by pwalsh** [comment]
> My basic 2c: let's not build another separate webapp please 😄 - instead could we integrate this with other existing apps / products.

The majority of the work ( see https://github.com/frictionlessdata/datapackage-ui/issues/228 ) is to create a reusable component for use in other apps. Current targets include Data Curator (desktop), possibly datahub.io, and possibly for embedding in the specs site.

**Comment by pwalsh** [comment]
@roll there is no *requirement* to use JSON Editor - the new UI is quite different from a normal form, and JSON Editor is designed around auto-generating "normal" web forms.

**Comment by roll** [comment]
@vitorbaptista (cc @pwalsh)
Please review - https://waffle.io/frictionlessdata/implementations. It's in current estimated in hours.

**Comment by roll** [comment]
SPLIT
  - #230
  - #231 
  - #232 
  - #233
  - https://github.com/frictionlessdata/tableschema-ui/issues/1

**Comment by rufuspollock** [comment]
@pwalsh @roll who does one talk to re implementation here and reuse in other apps. We're building something like this ourselves atm and i am not really clear who to talk to and where 😄
