### ISSUE TITLE
Design and bootstrap MVP

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-ui#230]
# Overview

We're going to start the whole `tableschema/datapackage-ui` work and have to make all kind of middle-level archetural decisions and boostrap the dev process. We already have the [goodtables-ui](https://github.com/frictionlessdata/goodtables-ui) to base our work on.

# Description

We want to allow users to create, edit and validate Data Packages from a web interface. We have an earlier version of this library [here](http://datapackagist.openknowledge.io). While we consider this implementation to be a bit flawed, it does show all the moving parts and useful implementation approaches for building out `datapackage-ui`.

# Requirements

- Create a new Data Package
- Edit an existing Data Package
- Validate a Data Package
- Download as a datapackage.json descriptor

# Visual design

- Coded version of above: http://p.smth.uk/packagist/
- Source: https://github.com/smth/packagist/tree/master
- Build: https://github.com/smth/packagist/tree/gh-pages

# Tasks

- [x] design and bootstrap the repository based on the `goodtables-ui` codebase. It includes the workflow for building, testing, publishing etc
- [x] design and bootstrap general component approach: we use `react` shipped with `react-lite` as described in the `goodtables-ui`'s [technical overview](https://hackmd.io/JwZgRgpgZgxjYFoAmEZIQFgIYwIwIA4xgCEB2ANioIFYK0AGAJgyA===#goodtables-ui) and [usage documentation](https://github.com/frictionlessdata/goodtables-ui#goodtables-ui). This approach works good for every framework and as a bonus `react` is the most used framework in the frictionless data eco-system (in case of advanced usage and community contribution). 
- [x] design and bootstrap routing/state management: we don't need routing for the app and state management should be the simplest to write and maintain (probably not `redux`)
- [x] design and bootstrap all kind of low-level services like uploading, downloading, validating, storing data etc
- [x] design and bootstrap how to integrate an existent visual design [mockup](http://p.smth.uk/packagist/) into the codebase 
- [x] write all needed component prototypes to test/proof the technical decisions above

**Comment by roll** [comment]
DONE
