### ISSUE TITLE
Improve application codebase

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-ui#232]
# Overview

In #231 we've finished all required components. Here we should polish all kind of integrational aspects like building, end-to-end testing, publishing etc

# Tasks

- [x] write shore readme
- [x] review and fix found bugs
- [x] mature overall application design
- [x] optimize overall application speed
- [x] write basic unit tests for the components
- [ ] improve unit tests coverage to 80-90%
- [ ] write end-to-end tests for the whole app
- [ ] remove demo descriptor form the application
- [ ] ensure correct building, publishing etc (remove build from repo)
- [ ] rebase validation on `datapackage.validate` (update dp-js if needed)
