### ISSUE TITLE
Improve application visual design

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-ui#233]
# Overview

In #232 we've finished the MVP application but it contains some elements (probably small) that was missing from an initial visual [mockup](http://p.smth.uk/packagist/). It means it's been visually designed by developers and requires a polishing or completely new visual design.

# Tasks

- [ ] setup scss/use style sources
- [ ] implement status bar at the bottom (last action, status, collapsed errors)
- [ ] remove bootstrap from bundle
- [ ] fix html forms (id/name/laberFor/etc)
- [ ] fix preview code coloring
- [ ] fix resource settings under upload input
- [ ] fix field data rows overlay 
- [ ] fix fonts loading
