### ISSUE TITLE
Implement standalone table schema editor

### ISSUE THREAD

**Issue by roll** [frictionlessdata/datapackage-ui#234]
# Overview 

We've created an `EditorPackage` - http://frictionlessdata.github.io/datapackage-ui/ - and all underlaying components including `EditorSchema`. We need a relatively small amount of work to add standalone mode to `EditorSchema` component to implement table schema editor app.

---

_From @pwalsh_

# Description

We want to allow users to create, edit and validate Table Schemas from a web interface.

We have an earlier version of a similar library [here](http://datapackagist.openknowledge.io), for Data Packages. While we consider this implementation to be a bit flawed, it does show all the moving parts and useful implementation approaches for building out `tableschema-ui`.

The most important component is the use of [json-editor](https://github.com/jdorn/json-editor) to generate web forms out of JSON Schema files.

# Tasks

- [ ] Farm out from https://github.com/frictionlessdata/datapackage-ui
- [ ] Create a new Table Schema
- [ ] Edit an existing Table Schema
- [ ] Validate a Table Schema
- [ ] Download as a `tableschema.json` descriptor
- [ ] Tests

**Comment by roll** [comment]
DONE https://github.com/frictionlessdata/tableschema-ui
