### ISSUE TITLE
Move "gh-pages" branch to "master"

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/datapackage-ui#241]
## Tasks

- [x] Tag the current HEAD as "old version" or similar (ideally something more descriptive)
- [x] Merge "gh-pages" to "master"
- [x] Configure GitHub Pages to deploy "master" by default
